# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anchor < Formula
  desc ""
  homepage "https://github.com/SongStitch/anchor"
  version "0.0.19"
  depends_on :macos

  url "https://github.com/SongStitch/anchor/releases/download/v0.0.19/anchor_0.0.19_darwin_all.tar.gz"
  sha256 "947eed2f1861846c070ae55d68f6f5d09e22397a84a56963321ea84c8d217b0c"

  def install
    bin.install "anchor"
  end
end
