# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anchor < Formula
  desc ""
  homepage "https://github.com/SongStitch/anchor"
  version "0.0.15"
  depends_on :macos

  url "https://github.com/SongStitch/anchor/releases/download/v0.0.15/anchor_0.0.15_darwin_all.tar.gz"
  sha256 "a78fcee18e2035363fc2ca78524259875f7a8915af8721c298ee38d784211f2c"

  def install
    bin.install "anchor"
  end
end
