# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anchor < Formula
  desc ""
  homepage "https://github.com/SongStitch/anchor"
  version "0.0.16"
  depends_on :macos

  url "https://github.com/SongStitch/anchor/releases/download/v0.0.16/anchor_0.0.16_darwin_all.tar.gz"
  sha256 "f8717e0bf3e8d3fc49cdc84a1b35b2674a7040aff46c6983af0dac821b33fcda"

  def install
    bin.install "anchor"
  end
end
